# Use mongo/mongo as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo_db1
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./data /data/db